-- CreateEnum
CREATE TYPE "SegmentoGrafica" AS ENUM ('ROTULOS_ETIQUETAS', 'OFFSET_COMERCIAL', 'COMUNICACAO_VISUAL', 'ESTAMPARIA_VESTUARIO', 'BRINDES_PERSONALIZADOS', 'EMBALAGEM_CARTONAGEM', 'EDITORIAL_LIVRO', 'CORTE_LASER_ACRILICO', 'GRAFICA_RAPIDA', 'OUTRO');

-- AlterTable
ALTER TABLE "graficas" ADD COLUMN     "segmento" "SegmentoGrafica",
ADD COLUMN     "segmentoOutro" TEXT;
